# Numpy Problems

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 100, (5, 5))

In [3]:
arr

array([[88, 13,  3, 87, 31],
       [66, 97, 10, 76, 67],
       [42, 90, 98, 94, 23],
       [18,  4,  9, 10,  6],
       [50, 13, 11, 29, 85]])

In [4]:
# Average of second column

np.mean(arr[:, 1])

np.float64(43.4)

In [11]:
print(arr)

arr[:, 3:5]

[[88 13  3 87 31]
 [66 97 10 76 67]
 [42 90 98 94 23]
 [18  4  9 10  6]
 [50 13 11 29 85]]


array([[87, 31],
       [76, 67],
       [94, 23],
       [10,  6],
       [29, 85]])

In [7]:
# average value of first 5 rows of 3rd and 4th column

avg = np.mean(arr[:, 3:5])

print(avg)

50.8


In [16]:
# COMPUTE ROWWISE SUM
# np.sum(mat, axis=1)   ### column-wise sums 
 
np.sum(arr, axis=1)

array([222, 316, 347,  47, 188])

In [17]:
# np.sum(mat, axis=0)   ### row-wise sums 

np.sum(arr, axis=0)

array([264, 217, 131, 296, 212])

In [ ]:
# maximum in each row
np.max(arr, axis=1) # rowwise max

array([88, 97, 98, 18, 85])

In [19]:
# maximum in each column

np.max(arr, axis=0) # columnwise max

array([88, 97, 98, 94, 85])

In [ ]:
max_means = np.mean(arr, axis=0) # for rowwise average

print("Maximum of average : ", max(max_means))

Maximum of average :  59.2
