# Indexing, slicing and iterating

In [1]:
import numpy as np

In [7]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
a**3

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441])

In [9]:
print(a[2])

4


In [10]:
print(a[2:5])

[ 4  9 16]


In [11]:
a[0:3:2] = 1000
print(a)

[1000    1 1000    9   16   25   36   49   64   81]


In [12]:
a[::-1]  # reversed a

array([  81,   64,   49,   36,   25,   16,    9, 1000,    1, 1000])

In [18]:
for i in a:
    print(i**(1/2), end=', ') # sqrt of each element

31.622776601683793, 1.0, 31.622776601683793, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 