In [1]:
import numpy as np

In [3]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)

In [4]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [5]:
b[2, 3]

np.int64(23)

In [6]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [7]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [8]:
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [11]:
b[1] # prints 1D array from 2D array

array([10, 11, 12, 13])

In [19]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [20]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [14]:
c.shape

(2, 2, 3)

In [15]:
c[1, ...]  # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [17]:
c[0, ...] # c[0]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [18]:
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])