In [8]:
import numpy as np

In [9]:
a = np.array([12, 32, 55, 100])
b = np.arange(4)

In [10]:
a - b

array([12, 31, 53, 97])

In [11]:
a + b

array([ 12,  33,  57, 103])

In [12]:
b**2

array([0, 1, 4, 9])

np.sin(a)

## Matrix Operations

In [15]:
A = np.array([[1, 2],
            [3, 4]])

In [16]:
B = np.array([[5, 6], [4, 7]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[5, 6],
       [4, 7]])

In [21]:
A * B # Elements-wise multiplication

array([[ 5, 12],
       [12, 28]])

In [22]:
A @ B # Matrix multiplication

array([[13, 20],
       [31, 46]])

In [24]:
A.dot(B) # alt - Matrix multiplication

array([[13, 20],
       [31, 46]])