In [1]:
import numpy as np

In [2]:
a = np.arange(15)

In [3]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
a = np.arange(15).reshape(3, 5)

In [9]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
a.shape # to check the shape of the array - in tuple

(3, 5)

In [17]:
a.ndim # to check the dimension of the array

2

In [18]:
a.dtype.name # types of elements in the array

'int64'

In [19]:
a.itemsize # size of each elements

8

In [21]:
a.size # total no. of elements in the array

15

In [22]:
type(a)

numpy.ndarray