In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 100, (3, 4))

In [3]:
a

array([[99, 83, 36, 54],
       [10, 76, 69, 43],
       [95, 67,  2, 47]], dtype=int32)

In [4]:
a.sum()

np.int64(681)

In [5]:
a.min()

np.int32(2)

In [6]:
a.max()

np.int32(99)

# Operations by:
## axis=0 --> column
## axis = 1 --> row

In [12]:
a.sum(axis=0) # Sum by columnwise

array([204, 226, 107, 144])

In [13]:
a.sum(axis=1) # Sum by row-wise

array([272, 198, 211])

In [14]:
a.min(axis=0)

array([10, 67,  2, 43], dtype=int32)

In [15]:
a.min(axis=1)

array([36, 10,  2], dtype=int32)

In [11]:
a.max(axis=0)

array([99, 83, 69, 54], dtype=int32)

In [16]:
a.max(axis=1)

array([99, 76, 95], dtype=int32)