# Universal functions

In [1]:
import numpy as np

In [2]:
B = np.arange(3)
B

array([0, 1, 2])

In [5]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [7]:
C = np.array([4, 5 , 6])

In [10]:
np.add(B, C)

array([4, 6, 8])